name: Release

on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
    test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: Install setuptools and 
          run: | 
            python -m pip install --upgrade setuptools wheel
            python -m pip install -r requirements-dev.txt
        - name: Test
          run: pytest tests/

    azure_test:
      name: Azure Test
      runs-on: ubuntu-latest
      environment:
        name: dev.azure
      # Not using OIDC Auth
      # permissions:
      #   id-token: write
      #   contents: read
      steps:
        # Not using CLI Auth
        # - name: 'Az CLI Login via OIDC'
        #  uses: azure/login@v1
        #  with:
        #    client-id: ${{ secrets.AZURE_CLIENT_ID }}
        #    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - uses: actions/checkout@v3
        - name: Set up Python 3.11
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: Install setuptools and
          run: | 
            python -m pip install --upgrade setuptools wheel
            python -m pip install -r requirements-dev.txt
        - name: Test
          run: pytest azure_tests/
          env:
            EMAIL: ${{ vars.EMAIL }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}


    publish:
      name: Publish
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
            python-version: 3.8
        - name: Install setuptools and 
          run: python -m pip install --upgrade setuptools wheel
        - name: Build a binary wheel and a source tarball
          run: python setup.py build sdist bdist_wheel

        - name: Publish distribution ðŸ“¦ to PyPI
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_TOKEN }}
